/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 24, 2018 at 12:17:24 AM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <UIKit/UIView.h>
#import <SpringBoard/SBIconListPageControlDelegate.h>
#import <UIKit/UITextFieldDelegate.h>
#import <UIKit/UIGestureRecognizerDelegate.h>
#import <SpringBoard/SBIconScrollViewDelegate.h>
#import <libobjc.A.dylib/BSDescriptionProviding.h>
#import <SpringBoard/SBIconListViewDragDelegate.h>

@protocol SBFolderViewDelegate;
@class NSMutableArray, NSMutableSet, SBIconListView, SBIconViewMap, SBAppStatusBarSettingsAssertion, SBIconLayoutOverrideStrategy, SBIconListPageControl, SBIconScrollView, SBFolderTitleTextField, UIView, UISwipeGestureRecognizer, UITapGestureRecognizer, SBFolder, _UILegibilitySettings, NSArray, NSString;

@interface SBFolderView : UIView <SBIconListPageControlDelegate, UITextFieldDelegate, UIGestureRecognizerDelegate, SBIconScrollViewDelegate, BSDescriptionProviding, SBIconListViewDragDelegate> {

	NSMutableArray* _iconListViews;
	NSMutableSet* _scrollingDisabledReasons;
	NSMutableSet* _pageControlDisabledReasons;
	SBIconListView* _rotatingIconList;
	long long _minVisibleListViewIndex;
	long long _maxVisibleListViewIndex;
	long long _minAnimatingListViewIndex;
	long long _maxAnimatingListViewIndex;
	long long _disableUpdatingCurrentIconListCount;
	long long _firstDisplayedColumnOnCurrentList;
	BOOL _animatedScrolling;
	BOOL _isScalingViewBorrowed;
	BOOL _isSettingScrolling;
	SBIconViewMap* _viewMap;
	NSMutableArray* _scrollFrames;
	unsigned long long _scrollFrameCount;
	SBAppStatusBarSettingsAssertion* _hideStatusBarAssertion;
	unsigned long long _ignoreScrollingDidEndNotificationsCount;
	NSMutableArray* _scrollCompletionBlocks;
	NSMutableArray* _rotationCompletionBlocks;
	SBIconLayoutOverrideStrategy* _iconLayoutOverrideStrategy;
	SBIconListPageControl* _pageControl;
	SBIconScrollView* _scrollView;
	SBFolderTitleTextField* _titleTextField;
	UIView* _scalingView;
	UISwipeGestureRecognizer* _swipeToCancelReachabilityGestureRecognizer;
	UITapGestureRecognizer* _tapToCancelReachabilityGestureRecognizer;
	BOOL _isEditing;
	BOOL _isScrolling;
	BOOL _rotating;
	long long _currentPageIndex;
	double _statusBarHeight;
	id<SBFolderViewDelegate> _delegate;
	SBFolder* _folder;
	long long _orientation;
	double _effectiveStatusBarHeight;
	_UILegibilitySettings* _legibilitySettings;
	_UILegibilitySettings* _accessibilityLegibilitySettings;
	long long _animatingToOrientation;

}

@property (assign,getter=isRotating,nonatomic) BOOL rotating;                                               //@synthesize rotating=_rotating - In the implementation block
@property (nonatomic,readonly) UIView * scalingView; 
@property (getter=isScalingViewBorrowed,nonatomic,readonly) BOOL scalingViewBorrowed;                       //@synthesize isScalingViewBorrowed=_isScalingViewBorrowed - In the implementation block
@property (assign,nonatomic) long long orientation;                                                         //@synthesize orientation=_orientation - In the implementation block
@property (assign,getter=isScrolling,nonatomic) BOOL scrolling;                                             //@synthesize isScrolling=_isScrolling - In the implementation block
@property (nonatomic,retain) SBIconListPageControl * pageControl;                                           //@synthesize pageControl=_pageControl - In the implementation block
@property (getter=_titleTextField,nonatomic,readonly) SBFolderTitleTextField * titleTextField; 
@property (assign,nonatomic,__weak) id<SBFolderViewDelegate> delegate;                                      //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) SBFolder * folder;                                                             //@synthesize folder=_folder - In the implementation block
@property (nonatomic,retain) SBIconLayoutOverrideStrategy * iconLayoutOverrideStrategy; 
@property (getter=isEditing,nonatomic,readonly) BOOL editing;                                               //@synthesize isEditing=_isEditing - In the implementation block
@property (nonatomic,readonly) long long currentPageIndex;                                                  //@synthesize currentPageIndex=_currentPageIndex - In the implementation block
@property (nonatomic,copy,readonly) NSArray * iconListViews;                                                //@synthesize iconListViews=_iconListViews - In the implementation block
@property (nonatomic,readonly) unsigned long long iconListViewCount; 
@property (nonatomic,readonly) SBIconViewMap * viewMap; 
@property (assign,nonatomic) double statusBarHeight;                                                        //@synthesize statusBarHeight=_statusBarHeight - In the implementation block
@property (nonatomic,readonly) double effectiveStatusBarHeight;                                             //@synthesize effectiveStatusBarHeight=_effectiveStatusBarHeight - In the implementation block
@property (nonatomic,retain) _UILegibilitySettings * legibilitySettings;                                    //@synthesize legibilitySettings=_legibilitySettings - In the implementation block
@property (nonatomic,retain) _UILegibilitySettings * accessibilityLegibilitySettings;                       //@synthesize accessibilityLegibilitySettings=_accessibilityLegibilitySettings - In the implementation block
@property (assign,nonatomic) long long animatingToOrientation;                                              //@synthesize animatingToOrientation=_animatingToOrientation - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(unsigned long long)_countOfAdditionalPagesToKeepVisibleInOneDirection;
+(Class)_scrollViewClass;
-(UIView *)scalingView;
-(SBIconViewMap *)viewMap;
-(id)initWithFolder:(id)arg1 orientation:(long long)arg2 viewMap:(id)arg3 context:(id)arg4 ;
-(SBIconLayoutOverrideStrategy *)iconLayoutOverrideStrategy;
-(unsigned long long)iconListViewCount;
-(void)resetIconListViews;
-(void)updateIconListViews;
-(NSArray *)iconListViews;
-(void)_updateIconListFrames;
-(void)_updatePageControlToIndex:(long long)arg1 ;
-(void)_setScrollingDisabled:(BOOL)arg1 forReason:(id)arg2 ;
-(id)_newPageControl;
-(double)_offsetToCenterPageControlInSpaceForPageControl;
-(BOOL)shouldInstallFocusGuides;
-(BOOL)setCurrentPageIndex:(long long)arg1 animated:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(void)prepareToOpen;
-(id)iconListViewAtIndex:(unsigned long long)arg1 ;
-(void)layoutIconLists:(double)arg1 animationType:(long long)arg2 forceRelayout:(BOOL)arg3 ;
-(void)cancelScrolling;
-(void)animateScrollToPageZeroWithCompletionHandler:(/*^block*/id)arg1 ;
-(void)noteUserIsInteractingWithIcons;
-(void)_disableUserInteractionBeforeSignificantAnimation;
-(void)_enableUserInteractionAfterSignificantAnimation;
-(id)iconListView:(id)arg1 previewForDroppingIconDragItem:(id)arg2 proposedPreview:(id)arg3 ;
-(void)iconListView:(id)arg1 iconDragItem:(id)arg2 willAnimateDropWithAnimator:(id)arg3 ;
-(void)handleReachabilityActivated:(BOOL)arg1 animated:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(id)borrowScalingView;
-(void)returnScalingView;
-(void)pageControl:(id)arg1 didRecieveTouchInDirection:(int)arg2 ;
-(void)setIconLayoutOverrideStrategy:(SBIconLayoutOverrideStrategy *)arg1 ;
-(id)_legibilitySettingsWithPrimaryColor:(id)arg1 ;
-(id)currentIconListView;
-(BOOL)iconListView:(id)arg1 canHandleIconDropSession:(id)arg2 ;
-(void)iconListView:(id)arg1 iconDropSessionDidEnter:(id)arg2 ;
-(id)iconListView:(id)arg1 iconDropSessionDidUpdate:(id)arg2 ;
-(void)iconListView:(id)arg1 iconDropSession:(id)arg2 didPauseAtLocation:(CGPoint)arg3 ;
-(void)iconListView:(id)arg1 iconDropSessionDidExit:(id)arg2 ;
-(void)iconListView:(id)arg1 performIconDrop:(id)arg2 ;
-(BOOL)iconListView:(id)arg1 shouldAllowSpringLoadedInteractionForIconDragOnIconView:(id)arg2 ;
-(void)iconListView:(id)arg1 springLoadedInteractionForIconDragDidCompleteOnIconView:(id)arg2 ;
-(void)resetContentOffsetToCurrentPage;
-(void)setIconPageIndicatorImageSetCache:(id)arg1 ;
-(void)setAccessibilityLegibilitySettings:(_UILegibilitySettings *)arg1 ;
-(void)_addIconListView:(id)arg1 ;
-(void)_removeIconListView:(id)arg1 ;
-(unsigned long long)_countOfAdditionalPagesToKeepAnimatingInOneDirection;
-(double)_titleFontSize;
-(CGRect)_frameForScalingView;
-(BOOL)isScalingViewBorrowed;
-(void)_updateIconListContainment:(id)arg1 atIndex:(unsigned long long)arg2 ;
-(void)_currentPageIndexDidChange;
-(id)iconListViewAtPoint:(CGPoint)arg1 ;
-(void)willTransitionAnimated:(BOOL)arg1 withSettings:(id)arg2 ;
-(void)didTransitionAnimated:(BOOL)arg1 ;
-(void)_updateScalingViewFrame;
-(void)repositionForReachabilityActivated:(BOOL)arg1 animated:(BOOL)arg2 actions:(/*^block*/id)arg3 completion:(/*^block*/id)arg4 ;
-(CGRect)_iconListFrameForPageRect:(CGRect)arg1 atIndex:(unsigned long long)arg2 ;
-(BOOL)locationCountsAsInsideFolder:(CGPoint)arg1 ;
-(BOOL)_showsTitle;
-(void)fadeContentForMagnificationFraction:(double)arg1 ;
-(void)fadeContentForMinificationFraction:(double)arg1 ;
-(double)reachabilityYOffset;
-(double)effectiveStatusBarHeight;
-(double)_pageWidth;

-(void)_updateEditingStateAnimated:(BOOL)arg1 ;
-(void)tearDownListViews;
-(void)cleanUpAfterTransition;
-(BOOL)_updatesWallpaperRelativeCenter;

-(BOOL)_shouldIgnoreScrollingDidEndNotifications;
-(void)iconScrollViewDidCancelTouchTracking:(id)arg1 ;


-(long long)_pageIndexForOffset:(double)arg1 ;
-(BOOL)iconScrollView:(id)arg1 shouldSetContentOffset:(CGPoint)arg2 animated:(BOOL)arg3 ;
-(void)updateIconListIndexAndVisibility:(BOOL)arg1 ;
-(double)_scrollOffsetForPageAtIndex:(long long)arg1 ;
-(double)_scrollOffsetForFirstListView;
-(void)handleCancelReachabilityGesture:(id)arg1 ;
-(unsigned long long)_minusPageCount;
-(void)_purgeListViews;
-(void)_setAnimatedScrolling:(BOOL)arg1 ;
-(void)_setPageControlDisabled:(BOOL)arg1 forReason:(id)arg2 ;
-(void)_endScrollingTest;
-(void)_setCurrentPageIndex:(long long)arg1 deferringPageControlUpdate:(BOOL)arg2 ;
-(BOOL)_isValidPageIndex:(long long)arg1 ;
-(void)_setCurrentPageIndex:(long long)arg1 ;
-(void)_addScrollingCompletionBlock:(/*^block*/id)arg1 ;
-(void)_setScrollViewContentOffset:(CGPoint)arg1 animated:(BOOL)arg2 ;
-(void)_ignoreScrollingDidEndNotifications;
-(void)_unignoreScrollingDidEndNotifications;
-(id)_iconListViewAtIndex:(unsigned long long)arg1 ;
-(id)_createIconListViewForList:(id)arg1 ;
-(void)_addIconListViewsForModels:(id)arg1 ;
-(id)_iconListViewForList:(id)arg1 ;
-(CGSize)_scrollViewContentSize;
-(void)_resetIconListViews;
-(void)_updateIconListViews;
-(void)updateIconListIndexAndVisibility;

-(BOOL)_shouldDisableUpdatingCurrentIconList;

-(long long)lowestVisibleIconListIndexAndColumn:(long long*)arg1 columnsOnScreen:(long long*)arg2 totalLists:(unsigned long long)arg3 columnsPerList:(unsigned long long)arg4 ;

-(void)_pushDisableUpdateCurrentIconListCount;
-(id)_currentIconListView;

-(void)_popDisableUpdateCurrentIconListCount;
-(BOOL)_scrollViewThinksItsScrolling;
-(void)_setFolderName:(id)arg1 ;
-(void)_updateTitleLegibilitySettings;

-(void)iconScrollViewWillCancelTouchTracking:(id)arg1 ;
-(void)setPageControlAlpha:(double)arg1 ;
-(BOOL)doesPageContainIconListView:(long long)arg1 ;
-(CGRect)scalingViewFrame;

-(BOOL)_hasMinusPages;


-(id)iconListViewForTouch:(id)arg1 ;
-(id)iconListViewForDrag:(id)arg1 ;
-(_UILegibilitySettings *)accessibilityLegibilitySettings;
-(long long)animatingToOrientation;
-(void)setAnimatingToOrientation:(long long)arg1 ;
-(void)setScrolling:(BOOL)arg1 ;
-(void)setNeedsLayout;
-(void)layoutSubviews;
-(id<SBFolderViewDelegate>)delegate;
-(void)scrollViewWillEndDragging:(id)arg1 withVelocity:(CGPoint)arg2 targetContentOffset:(inout CGPoint*)arg3 ;
-(void)setDelegate:(id<SBFolderViewDelegate>)arg1 ;
-(void)dealloc;
-(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2 ;
-(void)didMoveToWindow;
-(NSString *)description;
-(void)scrollViewDidScroll:(id)arg1 ;
-(void)scrollViewWillBeginDragging:(id)arg1 ;
-(void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2 ;
-(void)scrollViewDidEndDecelerating:(id)arg1 ;
-(void)scrollViewDidEndScrollingAnimation:(id)arg1 ;
-(BOOL)gestureRecognizerShouldBegin:(id)arg1 ;
-(double)statusBarHeight;
-(long long)orientation;
-(id)scrollView;
-(BOOL)isRotating;
-(id)_interactionTintColor;
-(void)willMoveToWindow:(id)arg1 ;
-(void)didMoveToSuperview;
-(BOOL)textFieldShouldBeginEditing:(id)arg1 ;
-(CGSize)scrollView:(id)arg1 contentSizeForZoomScale:(double)arg2 withProposedSize:(CGSize)arg3 ;
-(void)willRotateToInterfaceOrientation:(long long)arg1 ;
-(BOOL)isEditing;
-(void)setEditing:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2 ;
-(void)didRotateFromInterfaceOrientation:(long long)arg1 ;
-(void)prepareForTransition;
-(void)setOrientation:(long long)arg1 ;
-(void)textFieldDidEndEditing:(id)arg1 ;
-(BOOL)textFieldShouldReturn:(id)arg1 ;
-(void)setLegibilitySettings:(_UILegibilitySettings *)arg1 ;
-(_UILegibilitySettings *)legibilitySettings;
-(void)setRotating:(BOOL)arg1 ;
-(BOOL)isScrolling;
-(void)_orientationDidChange:(long long)arg1 ;
-(void)setContentAlpha:(double)arg1 ;
-(SBIconListPageControl *)pageControl;
-(long long)currentPageIndex;
-(SBFolder *)folder;
-(void)setFolder:(SBFolder *)arg1 ;
-(void)_layoutSubviews;
-(id)_titleTextField;
-(BOOL)setCurrentPageIndex:(long long)arg1 animated:(BOOL)arg2 ;
-(void)_backgroundContrastDidChange:(id)arg1 ;
-(void)setPageControl:(SBIconListPageControl *)arg1 ;
-(void)setPageControlHidden:(BOOL)arg1 ;
-(void)setStatusBarHeight:(double)arg1 ;
-(id)succinctDescription;
-(id)descriptionWithMultilinePrefix:(id)arg1 ;
-(id)descriptionBuilderWithMultilinePrefix:(id)arg1 ;
-(id)succinctDescriptionBuilder;
@end
